### ISSUE TITLE
IOS keyboard not disappears.

### ISSUE THREAD

**Issue by sajjadjaved01** [10play/10tap-editor#109]
Hi, im unable to close the keyboard on IOS device its working great on Android. 
Also Return On Keybaord is not closing the Keyboard.

https://github.com/10play/10tap-editor/assets/10374846/8f9d0e8b-5b9c-445e-bb65-a9bc06e7e6ab

` <SafeAreaView style={styles.fullScreen}>
      <RichText
        startInLoadingState={true}
        onLoad={() => {
          const json = convertSchemaToJSON(params.content);
          editor.setContent(JSON.parse(json));
        }}
        editor={editor}
      />
      <KeyboardAvoidingView
        behavior={Platform.OS === "ios" ? "padding" : "height"}
        style={styles.keyboardAvoidingView}
      >
        <Toolbar editor={editor} />
      </KeyboardAvoidingView>
    </SafeAreaView>`

**Comment by 17Amir17** [comment]
Hey @sajjadjaved01 
When do you expect the keyboard to close? Pressing return will add a new line, you could add a button to the header to dismiss the keyboard like apple notes does

**Comment by sajjadjaved01** [comment]
kindly guide me how can i achieve that like Apple notes ?

**Comment by 17Amir17** [comment]
Sure

You can add a button (in the toolbar, header or somewhere else) and use the bridge instance to `blur` the editor

```ts
      <TouchableOpacity onPress={() => editor.blur()}>
      ......
      </TouchableOpacity>
```

**Comment by 17Amir17** [comment]
Closing for now, let us know if something is not working as expected

**Comment by sajjadjaved01** [comment]
Hi @17Amir17 i have tried with blur() but this did't work as expected. 
Thanks
