### ISSUE TITLE
Advanced setup questions

### ISSUE THREAD

**Issue by jinwon7878** [10play/10tap-editor#111]
Hello! First of all, thank you so much for making such a nice rich text library available for react native 👍

I'm applying the advanced setup to implement 'readonly mode / multiple placeholder' and I'm not quite sure how the advanced setup implements its own bridgeExtension.

For example, if I implemented a custom bridgeExtension called **_PlaceholderWithTitleBridge_**, would this need to be added to both advancedEditor (Web: useTenTap-bridges) and advancedRichText (RN: useEditorBridge-bridgeExtensions)? I'm trying to understand the examples and documentation + source code on GitHub, but I'm not sure due to my lack of knowledge

And I'm using i18next's useTranslation hook for internalization support. With the useTranslation hook, I get 2 placeholder values (title, content) from the translate file. I functionized PlaceholderWithTitleBridge to use them in PlaceholderWithTitleBridge. However, this way there seems to be no way to pass the placeholder values from advancedEditor(web). This seems to be wrong.

Can anyone help me with this gap in my knowledge? If there is a clear path, I'd love to know.

I've attached the source code for comment. thank you!

```
// PlaceholderWithTitleBridge.ts (Custom BridgeExtension)

import Placeholder from "@tiptap/extension-placeholder";
import { BridgeExtension } from "@10play/tentap-editor";

type PlaceholderEditorWithTitleState = {};

type PlaceholderEditorWithTitleInstance = {};

declare module "@10play/tentap-editor" {
  interface BridgeState extends PlaceholderEditorWithTitleState {}
  interface EditorBridge extends PlaceholderEditorWithTitleInstance {}
}

export const PlaceholderWithTitleBridge = ({
  titlePlaceholder,
  contentPlaceholder,
}: {
  titlePlaceholder: string | undefined;
  contentPlaceholder: string | undefined;
}) =>
  new BridgeExtension<
    PlaceholderEditorWithTitleState,
    PlaceholderEditorWithTitleInstance
  >({
    tiptapExtension: Placeholder.configure({
      showOnlyCurrent: false,
      placeholder: ({ node }) => {
        if (node.type.name === "title") {
          return titlePlaceholder ?? ''; // need to fix
        } else {
          return contentPlaceholder ?? ''; // need to fix
        }
      },
    }),
    extendCSS: `
    h1.is-empty:nth-child(1)::before,
    p.is-empty:nth-child(2):last-child::before {
        color: #adb5bd;
        content: attr(data-placeholder);
        float: left;
        height: 0;
        pointer-events: none;
    }
  `,
  });
```

```
// AdvancedRichText.tsx (in RN component)

export default function AdvancedRichText() {
  const { t } = useTranslation(); // i18next
  const editor = useEditorBridge({
    customSource: editorHtml,
    bridgeExtensions: [
      CoreBridge,
      ListItemBridge,
      BulletListBridge,
      OrderedListBridge,
      TaskListBridge,
      PlaceholderWithTitleBridge({ titlePlaceholder: t("Editor:title_placeholder"), contentPlaceholder: t("Editor:content_placeholder") }),
    ],
    avoidIosKeyboard: true,
  });

  const content = useEditorContent(editor, { type: "json" });

  useEffect(() => {
    setTimeout(() => {
      editor.focus("start");
    }, 200); // autofocus:true not working
  }, []);

  useEffect(() => {
    StatusBar.setBarStyle("light-content"); // need to fix
  }, [content]);

  return (
    <BottomSheetModalProvider>
      <StatusBar barStyle={"light-content"} hidden={false} />
      <Container>
        <RichText editor={editor} />
      </Container>
    </BottomSheetModalProvider>
  );
}

```

```
// AdvancedEditor.tsx (in editor-web)

const DocumentWithTitle = Document.extend({
  content: "title block*",
});

const Title = Heading.extend({
  name: "title",
  group: "title",
  parseHTML: () => [{ tag: "h1:first-child" }],
}).configure({ levels: [1] });

export const AdvancedEditor = () => {
  const editor = useTenTap({
    bridges: [
      CoreBridge,
      ListItemBridge,
      BulletListBridge,
      OrderedListBridge,
      TaskListBridge,
      // PlaceholderWithTitleBridge({
      //   titlePlaceholder: ??,
      //   contentPlaceholder: ??,
      // }),
    ],
    tiptapOptions: {
      extensions: [DocumentWithTitle, Paragraph, Text, Title],
    },
  });

  return (
    <div style={{ backgroundColor: #FFF }}>
      <EditorContent editor={editor} />
    </div>
  );
};
```

**Comment by 17Amir17** [comment]
Hey @jinwon7878 thanks for the kind words!

Let's start with the concept, we basically generate a static html file that includes the editor logic, run that html file in a webview, and then communicate with it via messages. 
So a bridge has two parts, the web part that gets bundled into the generated html, and the native part which runs in the react native side. So regarding your first question, yes you need to add the bridge to useEditor on the native side and on the "web" side.
 
Try take a look and run the Advanced setup we have in the source code with the `CounterBridge`
You can see there that we add both in the web `AdvancedEditor.tsx` and also in the native `AdvancedRichText.tsx`

https://github.com/10play/10tap-editor/tree/main/example/src/Examples/Advanced

**Comment by Bayramito** [comment]
> Hey @jinwon7878 thanks for the kind words!
> 
> Let's start with the concept, we basically generate a static html file that includes the editor logic, run that html file in a webview, and then communicate with it via messages. So a bridge has two parts, the web part that gets bundled into the generated html, and the native part which runs in the react native side. So regarding your first question, yes you need to add the bridge to useEditor on the native side and on the "web" side.
> 
> Try take a look and run the Advanced setup we have in the source code with the `CounterBridge` You can see there that we add both in the web `AdvancedEditor.tsx` and also in the native `AdvancedRichText.tsx`
> 
> https://github.com/10play/10tap-editor/tree/main/example/src/Examples/Advanced

Thank you for your response, but i had same setup with same utilities but the editor did not even loaded
