### ISSUE TITLE
Toolbar not display on IOS

### ISSUE THREAD

**Issue by thunderfalco** [10play/10tap-editor#116]
![IMG_00F92A1553F1-1](https://github.com/10play/10tap-editor/assets/149560296/39cda6b6-f475-4044-84a8-fc3754e5e1f9)

As shown in the above picture, when i start input some text, but toolbar not display as expect, I use the demo code.

**Comment by GuySerfaty** [comment]
hey @thunderfalco did you try:
https://10play.github.io/10tap-editor/docs/examples/navHeader

**Comment by GuySerfaty** [comment]
@thunderfalco Im going to close it for now

**Comment by thunderfalco** [comment]
Thank you
