### ISSUE TITLE
When content contains \n, the editor can't render anything

### ISSUE THREAD

**Issue by thunderfalco** [10play/10tap-editor#128]
<img width="506" alt="image" src="https://github.com/10play/10tap-editor/assets/149560296/82cbda0e-3e11-498f-b1b0-36ad6c40e913">
<img width="538" alt="image" src="https://github.com/10play/10tap-editor/assets/149560296/df2212d9-c3eb-47f1-bb4a-f26252489e75">

![截屏 2024-06-08 23 12 52](https://github.com/10play/10tap-editor/assets/149560296/db4a3e43-4f44-4649-b2aa-42a7eebf8285)

**Comment by 17Amir17** [comment]
This might be fixed in https://github.com/10play/10tap-editor/pull/118
I'll try get it in this week

**Comment by 17Amir17** [comment]
Should be fixed in `0.5.1` 
If you want a new line you should use `<br />`

**Comment by thunderfalco** [comment]
Thank you
