### ISSUE TITLE
How to use lift, sink in TaskList

### ISSUE THREAD

**Issue by jinwon7878** [10play/10tap-editor#129]
Hi! I want to apply lift, sink on a taskList just like I do on a bulletList, orderedList. However, canLift, canSink appears to be false, so it looks like this is not supported yet.

Is there a way to create a custom bridge with advanced settings to make this possible, or is there another good way?

I would really appreciate an answer :)

[https://tiptap.dev/docs/editor/api/nodes/task-item](https://tiptap.dev/docs/editor/api/nodes/task-item)

**Comment by 17Amir17** [comment]
Here is a quick draft of this @jinwon7878  https://github.com/10play/10tap-editor/pull/130

It will take us some time to make sure everything is good and get this in but for now you can use this branch
