### ISSUE TITLE
Can I select paragraph of text but dont trigger keyboard open

### ISSUE THREAD

**Issue by longtm101898** [10play/10tap-editor#132]
Hello everyone,
I've question:
Can we select paragraph of text but **do not** automatically turn on the keyboard?

I'm in case:
1. User select paragraph of text and add format for the text, but keyboard's auto turned on -> taking up most of the display area

Regards and thanks

**Comment by 17Amir17** [comment]
I don't think there is a good way to do this. Not sure if this would work but maybe try dismissing the keyboard with the keyboard api, or setting the editor to readonly. But there is no current supported way of doing this
