### ISSUE TITLE
How to custom paragraph text style?

### ISSUE THREAD

**Issue by thunderfalco** [10play/10tap-editor#137]
I want change the paragraph style, I find that custom css document only contains how to change codeBridge style.

**Comment by GuySerfaty** [comment]
Hey @thunderfalco, did you check this example: https://10play.github.io/10tap-editor/docs/examples/customCss ?
you can change `customCodeBlockCSS` to be:
```

p {
    WHATEVER STYLE U WANT FOR <P>
}
```

**Comment by thunderfalco** [comment]
Thank you, I found that I use wrong syntax， an extra : added
```
p : {
}
```
Thank you
