### ISSUE TITLE
Does 10tap support tiptap-markdown extension

### ISSUE THREAD

**Issue by thunderfalco** [10play/10tap-editor#142]
Or how to integrate tiptap-markdown in 10tap

**Comment by GuySerfaty** [comment]
Hey @thunderfalco the basic setup and the tentapstarterkit supports markdown shortcuts for example, with the basic example you can `#` + SPACE to create an H1 node.
Is it that what you are looking for?

**Comment by thunderfalco** [comment]
I want to save content as markdown to export, Now I convert html to markdown and save it, but tasklist can't format well, tasklist converted to a list without checkbox

**Comment by GuySerfaty** [comment]
I see, so for doing that kind of thing you will have to use an advanced setup,
In case you are using 10tap for commercial use please consider upgrading to [10tap pro](https://10play.dev#10tap-pricing), we can then prioritize this and send over a pro example for that case.

Feel free to send us an email anytime to email@10play.dev

**Comment by thunderfalco** [comment]
Thank you
