### ISSUE TITLE
Can I set the selection background color?

### ISSUE THREAD

**Issue by jinwon7878** [10play/10tap-editor#144]
I am using the 10tap editor and I really appreciate it. However, I am facing an issue where I want to set the background color of selected text (p tag) to transparent using injectCSS or by applying styles in index.html through Advanced Settings. The CSS selectors such as ::selection and .Prosemirror::selection do not seem to work.

In dark mode, the selected text is not visible, which is a critical issue for me. Could you please provide advice on how to resolve this issue? Thank you.!

[in index.html (advanced settings)]
 .ProseMirror {
      caret-color: black !important; /* working O */
    }
    .ProseMirror::selection {
      background: red !important; /* working X */
      color: green !important; /* working X */
    }
    p::selection {
      background: red !important; /* working X */
      color: green !important; /* working X */
    }
    p::-moz-selection {
      background: transparent !important; /* working X */
    }
    p {
      font-size: 15px; /* working O */
      line-height: 24px; /* working O */
      margin: 2px 0; /* working O */
    }

![IMG_B4E8804BCCDD-1](https://github.com/10play/10tap-editor/assets/117356612/62b9c6d5-8af8-4567-9d9f-f7fa35fa74a9)
![IMG_FBB1ECAB2734-1](https://github.com/10play/10tap-editor/assets/117356612/24dfbb5a-524b-47f8-9fb2-491bab763d7e)

**Comment by ororsatti** [comment]
what platform? ios or android?
on android I have managed to change the color of the selection using:
```
*::selection { 
background-color: << color >>;
}

**Comment by jinwon7878** [comment]
> what platform? ios or android? on android I have managed to change the color of the selection using:
> 
> ```
> *::selection { 
> background-color: << color >>;
> }
> ```

Thank you for your response!

IOS. Unfortunately, that code doesn't work for me.

**Comment by GuySerfaty** [comment]
hey @jinwon7878, while working on:
https://x.com/10play_software/status/1808501667215593521

I noticed that:
```
* {
color: red;
}
```

Will change the color of the iOS selection to red, iOS probably inspect the * color of the webpage inside the webview and by that color the selection, this solution + override the color inside the class `.ProseMirror` will give you full control on selection

so the final solution will look something like this:
```
const editor = useEditorBridge({
  ...,
  bridgeExtensions: [
    ...TenTapStartKit,
    CodeBridge.configureCSS(`
    * {
      color: red;
    }

    #root div .ProseMirror * {
      color: #404040;
    }
    `), // Custom codeblock css
  ],
});
```

see: https://10play.github.io/10tap-editor/docs/examples/customCss

**Comment by jinwon7878** [comment]
> hey @jinwon7878, while working on: https://x.com/10play_software/status/1808501667215593521
> 
> I noticed that:
> 
> ```
> * {
> color: red;
> }
> ```
> 
> Will change the color of the iOS selection to red, iOS probably inspect the * color of the webpage inside the webview and by that color the selection, this solution + override the color inside the class `.ProseMirror` will give you full control on selection
> 
> so the final solution will look something like this:
> 
> ```
> const editor = useEditorBridge({
>   ...,
>   bridgeExtensions: [
>     ...TenTapStartKit,
>     CodeBridge.configureCSS(`
>     * {
>       color: red;
>     }
> 
>     #root div .ProseMirror * {
>       color: #404040;
>     }
>     `), // Custom codeblock css
>   ],
> });
> ```
> 
> see: https://10play.github.io/10tap-editor/docs/examples/customCss

I tried it, but this seems to be the way to change the font color - it doesn't change the background color while it's a selection via dragging, it's still there.

If there's something I'm missing, I'd appreciate it if you could let me know 😢.

![IMG_44EEFEAC3B95-1](https://github.com/10play/10tap-editor/assets/117356612/a44b5b46-95ac-413b-ac7a-8f335bb3c96f)
![IMG_D42D50258EDA-1](https://github.com/10play/10tap-editor/assets/117356612/2fa1bbd6-daa7-4e3a-87a0-623bf8acef7a)
