### ISSUE TITLE
[BUG-Question?]: Excessive state updates when updating content via `useBridgeState`

### ISSUE THREAD

**Issue by jbernhardt-x-team** [10play/10tap-editor#152]
**Describe the bug**
I'm currently doing a simple implementation of the `RichText` component where I have my component render the [Basic Example ](https://10play.github.io/10tap-editor/docs/examples/basic) and receive a prop to set the editor content.  In order to use `setContent` I use the `editor` value returned by the `useEditorBridge`. I also use the `useBridgeState` hook to get other values, like `isFocused` etc. The problem comes when I call `editor.setContent(props.content)` (currently called from a `useEffect`) my component starts getting infinite state renders but the content is still set. If I remove the `useBridgeState` hook from my component and do the same `editor.setContent(props.content)` I dont get unwanted state updates. I tried to check the hooks implementation and see if there could be any missing use of `useCallback` or `useMemo` but I couldnt spot anything obvious. 

I don't know if I should be setting the content differently in order not to trigger infinite state renders. 

**To Reproduce**
```JavaScript
const RichTextEditor = ({
  editorContent = null,
  isDisabled = false
}) => {
  const editor = useEditorBridge({
    editable: !isDisabled,
    avoidIosKeyboard: true,
    theme: {
      webviewContainer: {
        paddingHorizontal: 10
      }
    }
  });

//with the hook, excessive renders, without the hook, all good
 const bridgeState = useBridgeState(editor);


  useEffect(() => {
    if (editorContent) {
      editor.setContent(editorContent);
    }
  }, [editorContent, editor]);

  return (
    <View style={styles.container}>
      <RichText editor={editor} nestedScrollEnabled />
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : null}
        keyboardVerticalOffset={50}
        style={styles.keyboardAvoidingView}
      >
        <Toolbar editor={editor} items={TOOLBAR_ITEMS} />
      </KeyboardAvoidingView>
    </View>
  );
};


```

**Comment by 17Amir17** [comment]
Hey @jbernhardt-x-team 
The goto way to set the editors initial content is to use the `initalContent` prop. 
The `useBridgeState` hook will trigger a render on each state change, if this does not fit your specific needs you could probably create your own hook that will re-render only on specific state changes

In case you are using 10tap for commercial use please consider upgrading to [10tap pro](https://10play.dev/#10tap-pricing)
Feel free to send us an email anytime to [email@10play.dev](mailto:email@10play.dev)
