### ISSUE TITLE
Customizing link formatting when using the insert link toolbar item

### ISSUE THREAD

**Issue by dlayton66** [10play/10tap-editor#153]
Hi there,

Currently when I'm converting some text to a link using the insert link toolbar item, the href is set to whatever I type in the insert box, e.g. `href="google.com"`.  Is there any way to make it so everything typed into this box is prepended with "http://" if it's not already?  I'd like it so `href="google.com"` is saved as `href="http://google.com"` so the links will be opened as web urls.

I tried overriding the behavior of tiptap's `editor.setLink` like this, but it didn't work:

```
export const LinkExtension = {
  addCommands() {
    return {
      setLink: (attributes) => ({ commands }) => {
        let { href } = attributes;

        if (!/^https?:\/\//i.test(href)) {
          href = `http://${href}`;
        }

        return commands.setMark(this.name, { ...attributes, href });
      },
    }
  },
}

  const editor = useEditorBridge({
    autofocus: true,
    avoidIosKeyboard: true,
    initialContent,
    onChange: () => debouncedOnChange(editor.getHTML()),
    bridgeExtensions: [
      ...TenTapStartKit,
      CoreBridge.configureCSS(customCSS),
      LinkBridge.extendExtension(LinkExtension)
    ]
  });
```

Any ideas?  Any help would be much appreciated, thanks!

**Comment by 17Amir17** [comment]
Hey, unfortunately as of now we do not support adding/modifying commands on the simple setup.
I see two options:
1. Use the [advanced setup](https://10play.github.io/10tap-editor/docs/setup/advancedSetup) and customize the link extension there
2. Create your own link toolbar and handle the url conversion before calling `setLink`

This does however seem like a common use-case so we might add this by default.

In case you are using 10tap for commercial use please consider upgrading to [10tap pro](https://10play.dev/#10tap-pricing)
Feel free to send us an email anytime to [email@10play.dev](mailto:email@10play.dev)
