### ISSUE TITLE
[BUG]: Android build failing for react native 0.74.3

### ISSUE THREAD

**Issue by mbpictures** [10play/10tap-editor#157]
**Describe the bug**
I'm using react native 0.74.3 and installed 10tap-editor as recommended. When I build for android, I'm getting this build error:
```
> Failed to apply plugin 'com.facebook.react'.
   > The value for property 'languageVersion' is final and cannot be changed any further.
```

**To Reproduce**
1. Create project with react native 0.74.3
2. Install 10tap-editor
3. try to build for android

**Expected behavior**
Working build.

**Screenshots**

**Comment by 17Amir17** [comment]
Hey! Did you create the app with expo or react-native-cli?

**Comment by mbpictures** [comment]
With the react-native-cli

**Comment by 17Amir17** [comment]
Will take a look when I get the change 👍

**Comment by 17Amir17** [comment]
Hey @mbpictures just managed to run with these deps
```json
  "dependencies": {
    "@10play/tentap-editor": "^0.5.13",
    "react": "18.2.0",
    "react-native": "0.74.3",
    "react-native-webview": "^13.10.5"
  },
```

This might be caused by something else, would you mind create a new repository with the minimum amount of changes needed to reproduce? That would make it much easier to find the issue and solve if it is related to our package.

**Comment by mbpictures** [comment]
Hi!

Just found the issue. Adding this line to the android/build.gradle file resolved the issue:
```
apply plugin: "com.facebook.react.rootproject"
```

Thanks a lot for your time and help!

**Comment by guval-gh** [comment]
Hello 👋 

I use the module in my project (old project created with React Native "vanilla" and Expo added recently, still in bare workflow) 

```bash
"dependencies": {
    "@10play/tentap-editor": "^0.7.0",
    "react": "18.3.1",
    "react-native": "0.76.7",
    "expo": "52.0.41",
    "react-native-webview": "^13.8.7"
  }
```

...and this solved my problem. Thanks @mbpictures  👍 

> Hi!
> 
> Just found the issue. Adding this line to the android/build.gradle file resolved the issue:
> 
> ```
> apply plugin: "com.facebook.react.rootproject"
> ```
> 
> Thanks a lot for your time and help!
