### ISSUE TITLE
[BUG]: when setImage, cursor not easy to move

### ISSUE THREAD

**Issue by ryzencool** [10play/10tap-editor#164]
**Describe the bug**
now insert a image into editor, it is difficult to move cursor on the previous and end of message, especially on android

**Expected behavior**
when setImage, auto insert a empty line on previous and end of image

**Comment by medhouseit** [comment]
Try
```
editor.setContent(await editor.getHTML() + "<p></p>");
```

**Comment by ryzencool** [comment]
but if I want to insert some sentence before image when only insert a image(content only contains an image), it is diffcult move cursor to I expected position.

**Comment by 17Amir17** [comment]
Can think of a good way to do this in the basic setup however, if you use the advanced setup you can customize the `setImage` command to add an empty line before it

**Comment by ryzencool** [comment]
Thank you
