### ISSUE TITLE
Can't set selection background color by solution

### ISSUE THREAD

**Issue by jinwon7878** [10play/10tap-editor#166]
> hey @jinwon7878, while working on: https://x.com/10play_software/status/1808501667215593521
> 
> I noticed that:
> 
> ```
> * {
> color: red;
> }
> ```
> 
> Will change the color of the iOS selection to red, iOS probably inspect the * color of the webpage inside the webview and by that color the selection, this solution + override the color inside the class `.ProseMirror` will give you full control on selection
> 
> so the final solution will look something like this:
> 
> ```
> const editor = useEditorBridge({
>   ...,
>   bridgeExtensions: [
>     ...TenTapStartKit,
>     CodeBridge.configureCSS(`
>     * {
>       color: red;
>     }
> 
>     #root div .ProseMirror * {
>       color: #404040;
>     }
>     `), // Custom codeblock css
>   ],
> });
> ```
> 
> see: https://10play.github.io/10tap-editor/docs/examples/customCss

@GuySerfaty  I tried it, but this seems to be the way to change the font color - it doesn't change the background color while it's a selection via dragging, it's still there.

If there's something I'm missing, I'd appreciate it if you could let me know 😢.

![IMG_44EEFEAC3B95-1](https://github.com/10play/10tap-editor/assets/117356612/a44b5b46-95ac-413b-ac7a-8f335bb3c96f)
![IMG_D42D50258EDA-1](https://github.com/10play/10tap-editor/assets/117356612/2fa1bbd6-daa7-4e3a-87a0-623bf8acef7a)

_Originally posted by @jinwon7878 in https://github.com/10play/10tap-editor/issues/144#issuecomment-2206756607_

**Comment by GuySerfaty** [comment]
Can you share code?
on my side:
```
  const editor = useEditorBridge({
    autofocus: true,
    avoidIosKeyboard: true,
    bridgeExtensions: [
      ...TenTapStartKit,
      CodeBridge.configureCSS(`
      * {
        color: red;
      }
  
      #root div .ProseMirror * {
        color: #404040;
      }
      `), // Custom codeblock css
    ],
    initialContent,
  });
```
![image](https://github.com/user-attachments/assets/012f5c15-bb2b-412c-9c2e-0811649fda04)

**Comment by jinwon7878** [comment]
Here's my editor code in dark mode!! Thank you for your quick response :)

```
// editor in dark mode

const editor = useEditorBridge({
    bridgeExtensions: [
      CodeBridge.configureCSS(`
      * {
        color: ${color.neutral1}; // #E6E6E6
      }
      html, body {
         background-color: ${color.background}; // #212121 (black background)
         padding: 0 24px;
         font-size: 15px;
         color: ${color.neutral1}; // #E6E6E6 (white font color)
      }
      `),
    ],
    initialContent,
  });
```

As shown in the top photo, in dark mode (background color is black, text color is white), the selection background obscures the text. This selection background (similar to the font color) is only rectangularly wrapping around the text, not the margins.

**Comment by GuySerfaty** [comment]
@jinwon7878 - you didnt follow my solution at all

```
      #root div .ProseMirror * {
        color: blue;
      }

      * {
        color: red;
      }

      #root div .ProseMirror {
        background-color: black;
        padding: 0 24px;
        font-size: 15px;
      }
```

output:
![image](https://github.com/user-attachments/assets/a39bcac3-c6a0-47bd-89b7-d49c76bb780f)

please notice the:

```
      * {
        color: red;
      }
```

which does the trick here, change the selection color, then:

```

      #root div .ProseMirror * {
        color: blue;
      }
```

Will let you override the color to whatever you want to be the color of the actual text
