### ISSUE TITLE
[PRO]: MentionBridge example not working on latest versions

### ISSUE THREAD

**Issue by zzorba** [10play/10tap-editor#167]
**Describe the bug**
It seems like after typing a Mention and selecting one (which causes it to be inserted), the backspace key stops working until you use a directional arrow. Once you use a directional arrow, backspace starts working again.  Doing some debugging, it seems like taking any action on the editor at all causes this to hapeen.  

This bug does not reproduce on version 0.5.8, but after upgrading to 0.5.12 and 0.5.13 (and rebuilding the editor), it happens consistently.

**To Reproduce**
1. Open the MentionBridge paid example.
2. Change of 10play/10tap-editor to 0.5.13.
3. Run yarn editor:build 
4. Open in simulator (iOS), type an @ and then select a mention.
5. Try to press the backspace key.

**Expected behavior**
Backspace key should keep working.

**Comment by 17Amir17** [comment]
We're looking into this - seems to be some dependency issue caused by https://github.com/10play/10Tap-Editor/commit/26000271ccf4f0b95c359672015895f8dca21d5f

**Comment by 17Amir17** [comment]
Should be fixed on `0.5.15`

**Comment by zzorba** [comment]
Thank you, it's working great now!
