### ISSUE TITLE
[BUG]: Editor isn't ready yet and setting content not working

### ISSUE THREAD

**Issue by mbpictures** [10play/10tap-editor#175]
**Describe the bug**
I'm using the `useEditorBridge()` hook inside a modal component and on the mount of the component, I'm getting an "Editor isn't ready yet" warning.

**To Reproduce**
This is my modal component:
```TS
export const TextEditorModal = ({
    isVisible,
    onClose,
    content
}: {
    isVisible: boolean,
    onClose: (text: string) => unknown,
    content?: string
}) => {
    const theme = useTheme();

    const editor = useEditorBridge({
        initialContent: content
    });

    useEffect(() => {
        if (!content || !isVisible) {
            return;
        }
        editor.setContent(content);
    }, [content, isVisible]);

    const handleClose = () => {
        editor.getHTML().then(onClose);
    }

    return (
        <Modal
            style={{
                backgroundColor: theme.colors.background,
                padding: 12,
                margin: 0,
                width,
                height
            }}
            isVisible={isVisible}
            onBackButtonPress={handleClose}
        >
            <CustomIconButton icon={"chevron-left"} onPress={handleClose} />
            <RichText editor={editor} />
            <KeyboardAvoidingView
                behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
                style={exampleStyles.keyboardAvoidingView}
            >
                <Toolbar editor={editor} />
            </KeyboardAvoidingView>
        </Modal>
    )
};
```

**Expected behavior**
Content is updating once the useEffect hook triggers the setContent method. No warnings.

**Screenshots**

**Comment by 17Amir17** [comment]
Hey @mbpictures the issue here is that it takes some time for the editor to initialize and accept messages, that warning is thrown because it received a message before the editor can do anything about it.

You can know the editor is ready from the editor state, try update your code to
```tsx
    useEffect(() => {
        if (!content || !isVisible || !editor.getEditorState().isReady) {
            return;
        }
        editor.setContent(content);
    }, [content, isVisible]);
```

Of course this will not call setContent if it is not ready yet, but the initial content should be loaded from the prop anyways, alternatively you could list for isReady updates with [useBridgeState](https://10play.github.io/10tap-editor/docs/api/BridgeState#usebridgestate)

**Comment by mbpictures** [comment]
Thanks for this hint!

Even when I update my code like this, I'm getting the same warning:

```TS
    const editor = useEditorBridge({
        initialContent: content
    });
    const editorState = useBridgeState(editor);

    useEffect(() => {
        if (!content || !isVisible || !editorState.isReady) {
            return;
        }
        editor.setContent(content);
    }, [isVisible, editorState.isReady]);
```

**Comment by jonhy751** [comment]
I also have this error

**Comment by mbpictures** [comment]
Update: even without setting the content at all I get the warning

**Comment by 17Amir17** [comment]
I'm unable to reproduce this, could you share a clean repo where this happens so I can investigate?

**Comment by jonhy751** [comment]
I'm creating

**Comment by jonhy751** [comment]
I created another repository, with Expo SDK 51 and the error did not occur.
The version I tried to use in production was SDK 49, could there be something related?

@17Amir17

**Comment by jonhy751** [comment]
I managed to reproduce the error...
this code returns the error:

`Editor isn't ready yet
    at Suspense
    at Freeze (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.taptest&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:135073:23)
    at DelayedFreeze (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.taptest&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:135019:22)
    at RNSScreenStack
    at ScreenStack (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.taptest&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:135390:25)
    at NativeStackViewInner (http://10.0.2.2:8081/node_modules/expo-router/entry.bundle//&platform=android&dev=true&lazy=true&minify=false&app=com.taptest&modulesOnly=false&runModule=true&transform.routerRoot=app&transform.engine=hermes&transform.bytecode=true:132508:22)
    at RCTView
 


![code](https://github.com/user-attachments/assets/91eebc00-1295-4cb9-a583-ae83dced1276)
### I realized that when I do an if(test) return <Text>

**Comment by 17Amir17** [comment]
If this is only happening on new versions of expo, this might be caused from the `isExpo` util` not working 
https://github.com/10play/10tap-editor/blob/main/src/utils/misc.ts

**Comment by mbpictures** [comment]
I'm using a bare react native project, with one expo-module integrated (expo-av)

**Comment by jonhy751** [comment]
I realized that the editor needs an input to be rendered together.
In my code, the editor was rendered first and after a few milliseconds my input was rendered on the screen, causing the error.
I managed to solve it by setting the input to render right when the component started, together with the editor.

**Comment by ryzencool** [comment]
> I realized that the editor needs an input to be rendered together. In my code, the editor was rendered first and after a few milliseconds my input was rendered on the screen, causing the error. I managed to solve it by setting the input to render right when the component started, together with the editor.

I have encountered the same issue. Could you please share your code? Thank you very much.

**Comment by humungasaurus** [comment]
I'm also encountering this, would love some code examples of how it is solved

**Comment by hesamzkr** [comment]
Same I'm also having this issue and I'm not sure what's causing it or how to solve it

**Comment by 17Amir17** [comment]
Hey guys if you could provide a repo with the min amount of code to reproduce this we will have a better chance at solving this, since we cannot reproduce

**Comment by humungasaurus** [comment]
Too difficult to create a minimal repo, but I was able to repro this by removing then re-adding the conditional rendering of the RichText view.  Basically, it seems that if you instantiate the editor but dont render the webview, you get this warning.  However, if you instantiate the editor after the conditional you run into the "Renderred fewer hooks than expected" error

**Comment by Nesh108** [comment]
I'm not sure if this is related to this but I noticed that if I use `RichText` directly in a render, everything works well. But if I render it inside a renderItem of, say, `SectionList`, the component doesn't get rendered at all and I get the "Editor isn't ready".

**Comment by ryzencool** [comment]
> In my code, the editor was rendered first and after a few milliseconds my input was rendered on the screen, causing the error.

In my project, I only encounter this issue on Android，ios works well, On Android, occasionally, the editor page appears empty， not contains any content

**Comment by julian-gargicevich** [comment]
Getting this as well, it appears to be a race condition somewhere but I haven't been able to reproduce it consistently

**Comment by Sydney-o9** [comment]
I have the same error on Android, not on iOS

**Comment by Sydney-o9** [comment]
Should we modify `useEditorBridge()` to avoid sending messages before WebView loads?

https://github.com/10play/10tap-editor/blob/main/src/RichText/useEditorBridge.tsx#L100

**Comment by 17Amir17** [comment]
This should be fixed with https://github.com/10play/10tap-editor/pull/243
Let me know if this still occurs for anyone

**Comment by santhosh-umapathi-wikifolio** [comment]
Still it occurs, attached the video recording. I am on the version: `"@10play/tentap-editor": "^0.6.3",`

Its mostly on Android, 70% works, 30% keeps loading the editor

https://github.com/user-attachments/assets/21c3877e-07bd-45cf-8888-e839a03aed5e
