### ISSUE TITLE
[BUG]: maybe just documentation; minimum supported Android API level?

### ISSUE THREAD

**Issue by timheilman** [10play/10tap-editor#177]
**Describe the bug**
At Android API level 29 and above, it works great.  Using this library at Android API level 28 on an emulator, the editor simply remains a blank screen.  The promise returned by editor.getHTML() appears never to resolve.

**To Reproduce**
1. Use Android API level 28
2. install an app using tenTap editor
3. try to use it

**Expected behavior**
Mainly just that if this is anticipated, the supported Android API level is documented at "level 29 or above".  Currently according to https://apilevels.com/ that covers 86% of android devices out there.

If this is unanticipated, then I'd expect the editor to work at API level 28 the same as 29 and above.

**Comment by 17Amir17** [comment]
Hey thanks! 
Didn't have the time to look into why it is not working on API 28 - so for the time being we will add the to the docs
