### ISSUE TITLE
Is there no onFocus and onblur function?

### ISSUE THREAD

**Issue by jonhy751** [10play/10tap-editor#182]
I want to trigger a function as soon as it is focused on the input.

**Comment by GuySerfaty** [comment]
Hi @jonhy751, can you follow the issue template next time you open an issue? it help us to get back to you faster

for now, the best way to achieve what you asked is:

```
  const editorState = useBridgeState(editor);

  useEffect(() => {
    if (editorState.isFocused) {
      // Do water you want when the editor is focused
    }
  }, [editorState.isFocused]);
```

**Comment by 17Amir17** [comment]
In the future we are planning on implementing onFocus and onBlur into `useEditorBridge`

**Comment by GuySerfaty** [comment]
closing this for now
