### ISSUE TITLE
[BUG]: Editor isn't ready yet

### ISSUE THREAD

**Issue by jonhy751** [10play/10tap-editor#183]
**Describe the bug**

Even just declaring the editor, I received this message.
```
 const editor = useEditorBridge({
    bridgeExtensions: [
      ...TenTapStartKit,
      PlaceholderBridge.configureExtension({
        placeholder: "Escreva seu comentario",
      }),
    ],
    theme: {
      toolbar: {
        toolbarBody: { borderTopWidth: 0 },
        icon: {
          width: 26,
          height: 26,
        },
      },
      webview: {
        marginTop: -13,
        marginLeft: 8,
      },
    },
  });
```

**To Reproduce**
Declare editor in component...

**Expected behavior**
no receive warn in app

**Screenshots**
![image](https://github.com/user-attachments/assets/c6c11abb-1d7d-4d78-a8cf-37240c9ca94c)
![image](https://github.com/user-attachments/assets/caa45f78-0b84-40fe-89b3-eda06c4b235a)

**Comment by 17Amir17** [comment]
We had a similar issue here: https://github.com/10play/10tap-editor/issues/175
Can we get the full code?

**Comment by rustyonrampage** [comment]
I had the same issue. 
If you using useEditorBridge, you need to make sure there is RichText being rendered in the view.
When my RichText was in a conditional render, it was giving the warning. After that I created a separate component with both the brige hook and RichText. I rendered this component in coniditon and there's no warning.
