### ISSUE TITLE
[BUG]: Module '"@10play/tentap-editor"' has no exported member 'Toolbar'.

### ISSUE THREAD

**Issue by jaybuangan** [10play/10tap-editor#189]
**Describe the bug**
I'm following the instructions to add a custom toolbar https://10play.github.io/10tap-editor/docs/examples/colorKeyboard but when I try to import Toolbar from the  `@10play/tentap-editor` package, I get this message.

Module '"@10play/tentap-editor"' has no exported member 'Toolbar'.

this is what I have installed.
`@10play/tentap-editor": "^0.5.19"`

**Screenshots**
<img width="756" alt="Screenshot 2024-08-27 at 9 20 27 AM" src="https://github.com/user-attachments/assets/d99f32c9-ce27-486f-b62a-7be3046a0c44">

**Comment by 17Amir17** [comment]
I have not seen this, could you share a repo with this being reproduced?
