### ISSUE TITLE
[BUG]: how to get rid of the delay when rendering RichText

### ISSUE THREAD

**Issue by dlayton66** [10play/10tap-editor#190]
Hi there,

Is there any way to get rid of the slight delay that occurs when rendering the RichText component?  In my app we start out on a landing screen and then click on a box that takes us to a screen which uses the RichText component.  I've tried pre-rendering the component on the landing screen and passing it through params to the RichText screen, and I tried wrapping both screens in a context containing the component.  In both cases the delay still persisted.

Not sure if this is possible but I'm curious if y'all have looked into it at all.  Any help much appreciated, thanks!

**Comment by 17Amir17** [comment]
Hey,
Havn't been seeing too much of a delay to try any of this - but we have noticed delays when using fonts https://github.com/10play/10tap-editor/issues/69 could this be what you are seeing? Also how much of a delay are you seeing?

**Comment by 17Amir17** [comment]
Gonna close this since https://github.com/10play/10tap-editor/issues/69 is for this case
