### ISSUE TITLE
Dynamically Configurable Maximum Character Length for Editor

### ISSUE THREAD

**Issue by SecYJ** [10play/10tap-editor#203]
Hi I have a requirement which I have to define different maximum character length for different usage, and  I have tried the counter bridge solution to override the maximum length of editor but this is not what i want as this solution require restarting the entire script for it to take effect, I would like the maximum length of the editor able to configure and change from time to time without having to restart the script

reference: [https://github.com/10play/10tap-editor/blob/main/example/src/Examples/Advanced/CounterBridge.ts](url)

**Comment by 17Amir17** [comment]
Hey @SecYJ ,
Hey, specifically with this example you can use
```tsx
CounterBridge.configureExtension({
        limit: 10,
}),
```
