### ISSUE TITLE
[Not A BUG]: How to set/adjust Image size

### ISSUE THREAD

**Issue by NguyenHoangMinhkkkk** [10play/10tap-editor#209]
i'm using the function editor.setImage(imagePath) for input image.
i tried to crop the image into smaller size before setImage, but not work.
How we cannot <adjust> the image size after setImage. or <drag> it, or centering...

![Simulator Screenshot - iPhone 15 - 2024-10-10 at 10 34 14](https://github.com/user-attachments/assets/b1cc4525-d70f-403b-a44d-e5d49bf7e571)

https://github.com/user-attachments/assets/7e2da744-6070-451b-9293-3c6791aea981

**Comment by UmairHussain123** [comment]
do you provide further information about this screen code

**Comment by 17Amir17** [comment]
Hey, there is currently no way to do this. 
You can maybe check this out https://www.npmjs.com/package/tiptap-extension-resize-image and try get it to work with the advanced setup!
