### ISSUE TITLE
[BUG]: The toolbar doesn't show if pass onMessage in RichText

### ISSUE THREAD

**Issue by TuHuynh296** [10play/10tap-editor#219]
**Describe the bug**
The toolbar doesn't show if pass onMessage in RichText

**To Reproduce**
1. Define event onMessage in RichText
```typescript
<View style={exampleStyles.fullScreen}>
        <RichText
          editor={editor}
          onMessage={(e) => { // define here
            console.log('>>> event', e);
          }}
        />
</View>
``` 
3. The toolbar doesn't show anymore

**Expected behavior**
The toolbar should show normally after define message onMessage in RichText

**Screenshots**
- If I comment event onMessage the toolbar show normally:
![image](https://github.com/user-attachments/assets/41a1e8a3-f5d9-4ca4-aea3-10ac761312c0)

- If I use event onMessage the toolbar doesn't show normally:
![image](https://github.com/user-attachments/assets/86386ff4-d814-4710-8719-cc06c5c372e6)

**Debug**
After check the code of component RichText, I see that the event onMessage will overwrite event in onMessage in WebView and the logic in onWebViewMessage doesn't call and cause error?
![image](https://github.com/user-attachments/assets/bfe908aa-e80b-4a2a-a649-4c29ba43af75)

**Comment by 17Amir17** [comment]
Hey @TuHuynh296 
We rely on the `isFocused` state to display the toolbar, which we get from bridge.
We could probably propagate like you suggest in the screenshot, I'm curious what the use-case is?

**Comment by TuHuynh296** [comment]
My use-case is using onMessage of RichText to control event message of webview by item elemet in RichText, example I want to receive event listener after injectJS with addEvenListener for tag img to BridgeEditor, when user touch image in RichText I will catch it, so is this use-case is possible?

**Comment by 17Amir17** [comment]
This should be possible, the thing that might be hard here is sending the event when pressing the image. I think you will have to use the advanced setup

But also, we should probably make it possible to propagate `onMessage` cc @GuySerfaty for your thoughts

**Comment by TuHuynh296** [comment]
> This should be possible, the thing that might be hard here is sending the event when pressing the image. I think you will have to use the advanced setup
> 
> But also, we should probably make it possible to propagate `onMessage` cc @GuySerfaty for your thoughts 

Thank you so much @17Amir17 , I have relevant question that the advanced setup can emit event outside? The guildline document only setup for custom extensions from tiptap, could you share your ideal about catch event touch item in RichText by advanced setup?

**Comment by 17Amir17** [comment]
The advanced setup is basically a web app, you can add you own components, listener, etc...
Ideally for communicating you would use the existing bridge which would make it easier to access the value on the state
We have something a little similar for getting the documents focus state - see https://github.com/10play/10tap-editor/blob/main/src/bridges/core.ts

**Comment by TuHuynh296** [comment]
Thank you so much. The information provided in issue #207 addresses my needs.
