### ISSUE TITLE
Get editor schema

### ISSUE THREAD

**Issue by PedroPerpetua** [10play/10tap-editor#223]
I'm trying to implement some custom behaviour on text selection and processinh HTML; I was attempting to implement the solutions discribed [here](https://github.com/ueberdosis/tiptap/issues/369), however, they require access to the editor's schema. From my investigation into the docs and issues, you can create a custom schema, but there doesn't seem to be a way to obtain said schema at runtime. Is there a way to retrieve this from the editor?

**Comment by marcoscarvalho01** [comment]
I'm having the same problem here. I needed to get the current selected content or either use the selection {from,to} object from the editorState to indentify the content. However the from/to number does not have any corresponding indexes in the getText(), getHTML() or getJSON() methods.

A textBetween(from, to) method in the editorBridge would be perfect for such cases.

**Comment by 17Amir17** [comment]
Currently this is not possible in the built in editor, it is only possible with a custom extension using the advanced setup.
This does seem useful though so will add this to the roadmap

**Comment by GuySerfaty** [comment]
Im going to close this one, this is on our roadmap if you want to support adding this feature please email us on [email@10play.dev](mailto:email@10play.dev)
