### ISSUE TITLE
[BUG]: Custom keyboard not showing on iOS on React Native 0.76.2

### ISSUE THREAD

**Issue by quocluongha** [10play/10tap-editor#225]
**Describe the bug**
I followed custom keyboard [example](https://10play.github.io/10tap-editor/docs/examples/customKeyboard#full-solution). It worked on Android but there a blank space on iOS.

React Native: 0.76.2
@10play/tentap-editor: 0.5.23
iOS: 18.1

**To Reproduce**
Here is the reproduction repo:
https://github.com/quocluongha/tentap-editor-rn-0.76
Note: Please navigate to Create screen twice (go to Create screen -> go back -> go to Create screen again) since the editor is not rendered by the WebView on the time due to these issues: [#3615](https://github.com/react-native-webview/react-native-webview/pull/3615) and [#3631](https://github.com/react-native-webview/react-native-webview/pull/3631)

**Expected behavior**
The custom keyboard should be showing like in the documentation example.

**Screenshots**

https://github.com/user-attachments/assets/12fab737-5d7d-4f45-93c5-b6d9df162432

**Comment by 17Amir17** [comment]
@quocluongha Thanks for reporting!
I am able to reproduce, this is likely due to the latest RN version. We will work on this

**Comment by mlazari** [comment]
This seems to be related to the new architecture that is enabled by default in react-native 0.76. Disabling new architecture fixes the issue: https://github.com/mlazari/tentap-editor-rn-0.76/commit/f71d4862cb9bd205a09904034e9a7c70eeb3299e

https://github.com/user-attachments/assets/a02c8e22-4a20-41e9-a153-e0933c2ab061

**Comment by smidlma** [comment]
@17Amir17 Might be also this related to the new Arch ? I am not able to turn the new arch off for some reason removing the newArch flag from expo app config and rebulding the app is still using the new arch. So I cant tell if its directly related, but before upgrading to newest expo it was ok.



https://github.com/user-attachments/assets/9c269547-36b6-484f-9de7-2cc8a719eba5

**Comment by mlazari** [comment]
> for some reason removing the newArch flag from expo app config and rebulding the app is still using the new arch

@smidlma I think you need to set it to false (`newArchEnabled: false`) rather than remove it to disable the new arch, since new arch is enabled by default in react-native 0.76

**Comment by 17Amir17** [comment]
Hey,
This is related to bridge-less mode on the new arch (which is now enabled by default)
We have a fix https://github.com/10play/10tap-editor/pull/229 will likely get merged tomorrow

**Comment by GuySerfaty** [comment]
version 0.5.25 support bridgeless! please update here if this solve your issues

**Comment by quocluongha** [comment]
Upgrading to version 0.5.25 fixed the issue. Thank you very much for the quick fix. I am closing the issue.
