### ISSUE TITLE
[BUG]: when edit codeblock, press enter, will create new block

### ISSUE THREAD

**Issue by ryzencool** [10play/10tap-editor#228]
![QQ_1733225838395](https://github.com/user-attachments/assets/d2861506-4954-4600-9fa1-a3243d3b671d)

when press enter, tentap will create new codeblock, but expect behavior is still edit in current block.

**Comment by GuySerfaty** [comment]
hi @ryzencool - 10tap support [code mark](https://tiptap.dev/docs/editor/extensions/marks/code) and not [codeblock](https://tiptap.dev/docs/editor/extensions/nodes/code-block) 

We are planing to add support for codeblock, not sure when we will get to it yet.
For now, you can write your own bridge for codeblock with the [advanced setup](https://10play.github.io/10tap-editor/docs/setup/advancedSetup) or consider [10tap PRO](https://www.10play.dev/#10tap-pricing)

**Comment by ryzencool** [comment]
Thank you @GuySerfaty
