### ISSUE TITLE
[BUG]: How to convert JSONContent to HTML | setContent only accepts HTML string.

### ISSUE THREAD

**Issue by vyapak-khare** [10play/10tap-editor#230]
How can I convert JSONContent to HTML before calling setContent. Are there alternatives for generateHTML and generateText methods that are available in tiptap/core?
----

I am trying to build the functionality of editing an existing message. I want to repopulate my editor with a message as it is (with decorations). The problem is that I only have the JSONContent object available for that message. It is possible in React to use generateHTML method to convert JSONContent into HTML that can then be passed to the editor, but I cannot find a way to do the same in RN. 

generateHTML method (from tiptap/core) in RN would throw an error as the method expects an array of extensions or at least the StarterKit extension to be able to generate the HTML. TenTapStarterKit is clearly not of the same type as StarterKit. 

My solution? Force the editor to reload with initialContent (that accepts JSON). But considering I lift the editor state, that is a lot of rerendering I need to deal with. Plus this should not be the way.

My doubts..

1. Am I missing something? Is there an obvious way to do this?
2. Why doesn't editor.setContent accept JSON along with string.

## To Reproduce
No reproduction needed for this.

## Expected behavior
generateText and generateHTML methods that behave the same way tiptap/core methods do
OR
setContent accepts JSONContent as argument

**Comment by mnmnk43434** [comment]
Hello, we tried to solve the issue.

This is what we did:

Implement generateHTML and generateText methods in CoreBridge to convert JSONContent to HTML and plain text. Update setContent to accept JSONContent.

You can review changes in this commit: https://github.com/mnmnk43434/10play-10tap-editor-230/commit/88808385234fef80807e2935a4a6d084c5f7f3d8.


> [!CAUTION]
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.

---

If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

**Comment by vyapak-khare** [comment]
> Hello, we tried to solve the issue.
> 
> This is what we did:
> 
> Implement generateHTML and generateText methods in CoreBridge to convert JSONContent to HTML and plain text. Update setContent to accept JSONContent.
> 
> You can review changes in this commit: [mnmnk43434@8880838](https://github.com/mnmnk43434/10play-10tap-editor-230/commit/88808385234fef80807e2935a4a6d084c5f7f3d8).
> 
> Caution
> 
> Disclaimer: The concept of solution was created by AI and you should never copy paste this code before you check the correctness of generated code. Solution might not be complete, you should use this code as an inspiration only.
> 
> If you no longer want Latta AI to attempt solving issues on your repository, you can block this account.

Just tried it. The solution works well for a small number of cases. But it will start to fail the moment complex decorations and extensions are used. 

What about extensions like CodeBridge, TaskItem etc. I can definitely spend sometime and write a parser that is able to handle most cases, but can't this be an innate functionality of the editor.

**Comment by vyapak-khare** [comment]
```typescript
export const generateHTML = (node: JSONContent): string => {
  if (!node) return "";

  switch (node.type) {
    case "doc":
      return node.content?.map(generateHTML).join("") || "";

    case "paragraph":
      return `<p>${node.content?.map(generateHTML).join("") || ""}</p>`;

    case "text": {
      let text = node.text || "";
      if (node.marks) {
        node.marks.forEach((mark) => {
          switch (mark.type) {
            case "bold":
              text = `<strong>${text}</strong>`;
              break;
            case "italic":
              text = `<em>${text}</em>`;
              break;
            case "strike":
              text = `<s>${text}</s>`;
              break;
            case "code":
              text = `<code>${text}</code>`;
              break;
            case "link":
              const href = mark.attrs?.href || "#";
              text = `<a href="${href}" target="_blank">${text}</a>`;
              break;
          }
        });
      }
      return text;
    }

    case "mention":
      return `<span class="mention">@${node.attrs?.label || ""}</span>`;

    case "codeBlock":
      return `<pre><code>${node.content?.map(generateHTML).join("") || ""}</code></pre>`;

    case "bulletList":
      return `<ul>${node.content?.map(generateHTML).join("") || ""}</ul>`;

    case "orderedList": {
      const start = node.attrs?.start || 1;
      return `<ol start="${start}">${node.content?.map(generateHTML).join("") || ""}</ol>`;
    }

    case "listItem":
      return `<li>${node.content?.map(generateHTML).join("") || ""}</li>`;

    case "taskList":
      return `<ul class="task-list">${node.content?.map(generateHTML).join("") || ""}</ul>`;

    default:
      return "";
  }
};
``` 

This is what I have come up with up until now.. It still does not cover the entirety of possibilities.

**Comment by 17Amir17** [comment]
Hey @vyapak-khare, `setContent` should be able to accept JSON - I see it is a type issue we can fix that

**Comment by 17Amir17** [comment]
Should be fixed in latest version!
