### ISSUE TITLE
[PRO]: Pasting links creates duplicates

### ISSUE THREAD

**Issue by austinzumbro** [10play/10tap-editor#233]
**Describe the bug**
When pasting text that includes a link, the text immediately following the link is also linked.  

If the original copied text is: "Officers also <recovered a backpack> in Central Park on Friday that they believe..."
Once pasted into the editor, it becomes:  "Officers also <recovered a backpack>< in Central Park on >Friday that they believe..."

Where both <strings in brackets> are links. It looks like the link is being applied both to the original set of characters and the next set of characters of the same length. 

The duplication does not occur if there are not enough characters left in the pasted string to accommodate the link.  For example, if the original copied text is this:  "Officers also <recovered a backpack> in Central Park"
Then the paste works as expected.

**To Reproduce**
1. Copy text that includes a hyperlink and as many characters after the link as there are in the link.  Something like this should work:
After [The Times reported on the legal battle](https://www.nytimes.com/2024/07/24/business/media/rupert-murdoch-succession-fox.html) over the family trust in July, the paper, joined by several other news outlets, filed a motion to unseal the proceedings, citing the significant public interest in its outcome.
2. Paste it into the editor.
3. See that the link is duplicated as described.  In the above example, it would look like this:
After [The Times reported on the legal battle](https://www.nytimes.com/2024/07/24/business/media/rupert-murdoch-succession-fox.html)[ over the family trust in July, the pa](https://www.nytimes.com/2024/07/24/business/media/rupert-murdoch-succession-fox.html)per, joined by several other news outlets, filed a motion to unseal the proceedings, citing the significant public interest in its outcome.

**Screenshots**
![Simulator Screenshot - iPhone 16 Pro Max - 2024-12-09 at 15 39 45](https://github.com/user-attachments/assets/f493dd1d-e8d7-4614-a58e-b26298c257a0)

**Comment by GuySerfaty** [comment]
hi @austinzumbro can you email email@10play.dev with the email you purchased 10tap PRO? we have an issue with recognizing you as a PRO user

**Comment by GuySerfaty** [comment]
hi @austinzumbro - thanks for report that bug ! it should be fixed on version: `0.5.27`
