### ISSUE TITLE
[BUG]:  Font family does not work

### ISSUE THREAD

**Issue by Bayramito** [10play/10tap-editor#241]
I just wanted to change font family in the editor but did not work at all.

Here is the configuration
this is css part
![Ekran Resmi 2024-12-16 11 10 11](https://github.com/user-attachments/assets/63a070ea-c32d-4cf0-b506-4736d1ed92b2)

this is the injection
![Ekran Resmi 2024-12-16 11 10 30](https://github.com/user-attachments/assets/1c3cdec6-843b-41c6-98d3-4a070efb5f06)

my fonts are

Lemon-Milk-Pro-Bold
Lemon-Milk-Pro-Medium
Lemon-Milk-Pro-Ultra-Light

Am I doing something wrong ?

**Comment by 17Amir17** [comment]
Hey,
Did you see https://10play.github.io/10tap-editor/docs/examples/customCss#adding-custom-fonts?

**Comment by Bayramito** [comment]
> Hey, Did you see https://10play.github.io/10tap-editor/docs/examples/customCss#adding-custom-fonts?

Hey thanks for reply.. 

Yes finally figure it out. I have a small question, and i dont see reason to open a new topic about it.

Can we insert videos with 10tap at all ? or insert a custom html or something ? 

Is that possible?

**Comment by 17Amir17** [comment]
Yes this is possible with the advanced setup see: https://10play.github.io/10tap-editor/docs/setup/advancedSetup
You could create your own extension (or use something existing like https://github.com/sereneinserenade/tiptap-extension-video) and build a bridge for it. This does require some TipTap experience

Feel free to contact us at email@10play.dev if you need specific assistance or check out our pro plan at 10play.dev
