### ISSUE TITLE
[BUG]: V0.5.29 ../node_modules/@10play/tentap-editor contains an invalid package.json configuration. Consider raising this issue with the package maintainer(s).

### ISSUE THREAD

**Issue by AJPASHA** [10play/10tap-editor#245]
**Describe the bug**
There seems to be an issue with the package.json file after the most recent update. 

**To Reproduce**
1. `npx expo start`
2. failure on launching web version from the expo sandbox

**Comment by 17Amir17** [comment]
Hey! Where do you see this on a fresh expo app?

**Comment by themtaysw** [comment]
hey i am experiencing the same issue with the lastest version, could be related to some external package?
