### ISSUE TITLE
Dynamic css.

### ISSUE THREAD

**Issue by sleep9** [10play/10tap-editor#57]
Would be cool if there was a way to update the css for the editor. 
`CoreBridge.configureCSS(customCss),`

**Comment by GuySerfaty** [comment]
> Would be cool if there was a way to update the css for the editor. 
> 
> `CoreBridge.configureCSS(customCss),`
> 
>       

Hey @sleep9, did you check the docs? There is a way to update both the [css of the webview editor](https://10play.github.io/10tap-editor/docs/examples/customCss#addingoverriding-css) and also a way to customize the [theme](https://10play.github.io/10tap-editor/docs/examples/customTheme) of the react native side

**Comment by 17Amir17** [comment]
What is the use-case?

**Comment by sleep9** [comment]
Works great thanks!
