### ISSUE TITLE
Support for DropCursor extension?

### ISSUE THREAD

**Issue by earlybail** [10play/10tap-editor#65]
First off, this library seems amazing. I've struggled in the past with RN WYSIWYGs, so thank you for your work in bringing a dedicated & robust experience to the framework.

I'm working on a new app, and 10tap seems very promising after only playing with it for 10 minutes. The TaskList support is a deal-maker for us!

Do you plan to add support for the [DropCursor](https://tiptap.dev/docs/editor/api/extensions/dropcursor) extension? That would help a lot in making this thing feel like Notion et al.

**Comment by 17Amir17** [comment]
Thank you so much for your feedback! 
It should be simple to add this extension, I can add this
