### ISSUE TITLE
DropCursorBridge is not exported

### ISSUE THREAD

**Issue by mandrade2** [10play/10tap-editor#79]
Hey there! tried open a small PR for this but don't have write access. 

As the title says, the DropCursor bridge is there and all but is not exported on `src/index.tsx`. Super small fix

**Comment by 17Amir17** [comment]
Oh my bad, I will push a fix
Btw, you could fork this repo and open a pr between your fork and this repo

**Comment by 17Amir17** [comment]
Released!

**Comment by mandrade2** [comment]
> Oh my bad, I will push a fix Btw, you could fork this repo and open a pr between your fork and this repo

Oh didn't know this was a thing, great
