### ISSUE TITLE
Allow setting max characters limit

### ISSUE THREAD

**Issue by minimalknave127** [10play/10tap-editor#91]
Hello, is there a way to set a maximum character limit for the RichText component? I couldn’t find any information in the documentation, nor could I find details on making the element controlled to implement my own logic.

Thanks!

**Comment by 17Amir17** [comment]
Hey!
While this is not in our built it editor, this is possible with the (advanced setup)[https://10play.github.io/10tap-editor/docs/setup/advancedSetup] using tiptaps (Character Count)[https://tiptap.dev/docs/editor/api/extensions/character-count] extension. We have an example of this in the "Advanced" route in the app https://github.com/10play/10tap-editor/tree/main/example/src/Examples/Advanced


https://github.com/10play/10tap-editor/assets/36531255/16d425cd-75f0-4906-ba5d-d455faf4600d
