### ISSUE TITLE
Does this library support insert image and audio?

### ISSUE THREAD

**Issue by thunderfalco** [10play/10tap-editor#92]

**Comment by 17Amir17** [comment]
Hey!
Insert image is supported, we have an example for this here https://github.com/10play/10tap-editor/blob/main/example/src/Examples/CustomKeyboardExample.tsx 
As for audio, it is possible, but with the [Advanced Setup](https://10play.github.io/10tap-editor/docs/mainConcepts#advanced-usage) which requires some Tiptap work
