### ISSUE TITLE
Does this library support Table of TipTap

### ISSUE THREAD

**Issue by hieu2nd** [10play/10tap-editor#94]
I'm trying to add Table into 10tap-editor. Please help

**Comment by 17Amir17** [comment]
Hey @hieu2nd 
Have you checked out https://10play.github.io/10tap-editor/docs/mainConcepts#advanced-usage
And also the example provided here: https://github.com/10play/10tap-editor/tree/main/example/src/Examples/Advanced

If you have a special requirement and need extra assistance you can contact us at [email@10play.dev](mailto:email@10play.dev)
