### ISSUE TITLE
Basic example is crashing the app with the 'undefined is not a function' error

### ISSUE THREAD

**Issue by AgrYpn1a** [10play/10tap-editor#95]
I've installed the library via expo, as suggested in the documentation and have re-created my development build but during the application loading, it crashes wit the following error:
![image](https://github.com/10play/10tap-editor/assets/8715031/aa2f07c7-cc08-47d2-9934-548f4aba9818)

**Comment by 17Amir17** [comment]
Can you share more info? RN, Expo and Tentap versions along with the code you are using?
I am unable to reproduce this

**Comment by AgrYpn1a** [comment]
@17Amir17 Hey of course, sorry for not including it right away. 

Here are the versions:
 - `"@10play/tentap-editor": "^0.4.55"`,
 - `"react-native": "0.71.8"`,
 - `"expo": "~48.0.18"`


And the code:

```tsx
import React from 'react';
import { View } from 'react-native';
import { SafeAreaView, View, KeyboardAvoidingView, Platform, StyleSheet } from 'react-native';
import { RichText, Toolbar, useEditorBridge } from '@10play/tentap-editor';

export const RichTextInput = () => {
  const editor = useEditorBridge({
    autofocus: true,
    avoidIosKeyboard: true,
    initialContent,
  });

  return (
    <SafeAreaView style={exampleStyles.fullScreen}>
      <RichText editor={editor} />
      <KeyboardAvoidingView
        behavior={Platform.OS === 'ios' ? 'padding' : 'height'}
        style={exampleStyles.keyboardAvoidingView}
      >
        <Toolbar editor={editor} />
      </KeyboardAvoidingView>
    </SafeAreaView>
  );
};

const exampleStyles = StyleSheet.create({
  fullScreen: {
    flex: 1,
  },
  keyboardAvoidingView: {
    position: 'absolute',
    width: '100%',
    bottom: 0,
  },
});

const initialContent = `<p>This is a basic example!</p>`;
```

**Comment by 17Amir17** [comment]
Hey! So I was unable to reproduce again but taking another look at the error [repo for repro](https://github.com/17Amir17/10TapExpo)
Take a look at this issue, seems similar: https://github.com/10play/10tap-editor/issues/97

**Comment by AgrYpn1a** [comment]
@17Amir17 hey thanks, I will take a look and confirm whether that works or not.
