### ISSUE TITLE
Needed to add / commands in ReactNative App.

### ISSUE THREAD

**Issue by sajjadjaved01** [10play/10tap-editor#96]
Hi, 
I want to create **notion like editor using tiptap in react Native**
i want to implement the / commands in editor to use [Commands](https://tiptap.dev/docs/editor/experiments/commands)

![1_223aTv2WEZW8Tc78eY0J-A](https://github.com/10play/10tap-editor/assets/10374846/5975f16c-2ab5-46c8-b968-de30724c80d1)

This is in React, but i want it to be in React Native. 
I'm new here, Any help will be appricated. 
Thanks.

**Comment by 17Amir17** [comment]
So although this library is for react-native it is important to understand how it works, the `RichText` component is a webview that runs web tiptap code (with react). What the library provides is a bridge between the two. If you want to add additional functionality to the editor it is possible with https://10play.github.io/10tap-editor/docs/mainConcepts#advanced-usage. We have provided an example in `Examples` as-well.
With the advanced usage you can add the slash menu extension. When it comes to displaying the options you could either make them display with react-native components by writing you're own bridge to connect the too (look at some of the bridge's we wrote) however placing the menu dropdown will be complicated, so i'd recommend only doing this if the wantthe options in a toolbar. 
Alternatively you can render the menu inside the webview with regular web react components.
If you require more hands on assistance you may contact us at email@10play.dev

**Comment by sajjadjaved01** [comment]
I have mailed on this contact email but did't got any feedback. 
Kindly guide me how can i achive this.

**Comment by 17Amir17** [comment]
> I have mailed on this contact email but did't got any feedback. Kindly guide me how can i achive this.

Hey sorry about that something must have gone wrong since we didn't get it 
Try maybe from our [website](https://www.10play.dev/#:~:text=Go-,Premium,-Our%20champions%20says)
